name: tof-distance
author: vu-ase
source: https://github.com/VU-ASE/tof-distance
version: 0.0.1
description: A small service that gets the distance measured by a time of flight sensor and outputs it as a stream 


commands:
  build: make build
  run: ./bin/SERVICE_NAME

inputs: []

outputs: []

configuration:
  - name: frame-rate
    type: number
    value: 100
    tunable: true
  - name: multiplex
    type: number
    value: 1 # 0 or 1
    tunable: false 
  - name: channel
    type: number
    value: 0 # unused if multiplex is off
    tunable: false
  - name: bus
    type: number
    value: 5 
    tunable: false
